/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import entidades.Ejemplar;
import entidades.Lector;
import entidades.Prestamo;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.AutorData;
import modelo.Conexion;
import modelo.EjemplarData;
import modelo.LectorData;
import modelo.LibroData;
import modelo.MultaData;
import modelo.PrestamoData;

/**
 *
 * @author Chony
 */
public class ViewPrestamos extends javax.swing.JInternalFrame {

    private LectorData leda;
    private EjemplarData ejeda;
    private LibroData librod;
    private AutorData autda;
    private MultaData multda;
    private PrestamoData prestamo;
    private DefaultTableModel modelo;
    
    public ViewPrestamos() {
        initComponents();
        Conexion c=new Conexion();
        leda= new LectorData(c);
        ejeda=new EjemplarData(c);
        librod=new LibroData(c);
        autda=new AutorData(c);
        multda=new MultaData(c);
        prestamo=new PrestamoData(c);
        modelo=new DefaultTableModel(); 
        anularCampos();
        armarCabecera();
        
    }
    public void anularCampos(){
        jtNombreLector.setEnabled(false);
        jtApellidoLector.setEnabled(false);
        jtDniLector.setEnabled(false);
        jtNombreLibro.setEnabled(false);
        jcbEstadoLector.setEnabled(false);
        jbBuscarLibro.setEnabled(false);
        jtLibros.setEnabled(false);
        jbRegistrar.setEnabled(false);
        jbLimpiar.setEnabled(false);
        jdcFechaPrestamo.setEnabled(false);
    }
    public void habilitarCampos(){
        jtNombreLibro.setEnabled(true);
        jbBuscarLibro.setEnabled(true);
        jtLibros.setEnabled(true);
        jbLimpiar.setEnabled(true);
        jdcFechaPrestamo.setEnabled(true);
    }
    public void armarCabecera(){
        ArrayList<Object> columnas= new ArrayList<>();
        columnas.add("idEjemplar");
        columnas.add("Nombre Libro");
        columnas.add("Año");
        columnas.add("Autor");
        columnas.add("Estado");
        
        
        for(Object it: columnas){
            modelo.addColumn(it);
        }
        jtLibros.setModel(modelo);
        
    }
    public void llenarConLibros(){
        List<Ejemplar> list=ejeda.buscarEjemplar(jtNombreLibro.getText());
        for(Ejemplar e:list){
            modelo.addRow(new Object[]{e.getId_ejemplar(),e.getLibro().getNombre(),e.getLibro().getAño(),e.getLibro().getAutor(),e.getEstado()});
        }
    }
    public void limpiarTabla(){
        int a=modelo.getRowCount()-1;
        
        for(int i=a;i>=0;i--){
            modelo.removeRow(i);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtIdLector = new javax.swing.JTextPane();
        jbBuscarLector = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDniLector = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtApellidoLector = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtNombreLibro = new javax.swing.JTextPane();
        jbBuscarLibro = new javax.swing.JButton();
        jbRegistrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtNombreLector = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        jcbEstadoLector = new javax.swing.JCheckBox();
        jbSalir = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtLibros = new javax.swing.JTable();
        jbLimpiar = new javax.swing.JButton();
        jdcFechaPrestamo = new com.toedter.calendar.JDateChooser();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Gestión de Prestamos");

        jLabel2.setText("ID Lector:");

        jLabel3.setText("Nombre de Libro");

        jScrollPane1.setViewportView(jtIdLector);

        jbBuscarLector.setText("Buscar Lector");
        jbBuscarLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarLectorActionPerformed(evt);
            }
        });

        jLabel5.setText("Apellido:");

        jScrollPane2.setViewportView(jtDniLector);

        jLabel6.setText("DNI");

        jScrollPane4.setViewportView(jtApellidoLector);

        jScrollPane5.setViewportView(jtNombreLibro);

        jbBuscarLibro.setText("Buscar");
        jbBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarLibroActionPerformed(evt);
            }
        });

        jbRegistrar.setText("Registar Prestamo");
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre:");

        jScrollPane7.setViewportView(jtNombreLector);

        jcbEstadoLector.setText("Estado");
        jcbEstadoLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoLectorActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jtLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jtLibros);

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jbBuscarLibro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jbBuscarLector))
                            .addComponent(jcbEstadoLector))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8)
                            .addComponent(jSeparator1))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbRegistrar)
                        .addGap(180, 180, 180)
                        .addComponent(jbLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalir)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jdcFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jcbEstadoLector))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbBuscarLector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jbBuscarLibro))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jdcFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRegistrar)
                    .addComponent(jbLimpiar)
                    .addComponent(jbSalir))
                .addGap(178, 178, 178))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
      dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbBuscarLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarLectorActionPerformed
        Lector lector=new Lector();
        
        try{
            int id=Integer.parseInt(jtIdLector.getText());
            lector=leda.buscarLector(id);
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Error en id");
        }
        
        
        jtNombreLector.setText(lector.getNombreLector());
        jtApellidoLector.setText(lector.getApellidoLector());
        jtDniLector.setText(String.valueOf(lector.getDniLector()));
        jcbEstadoLector.setSelected(lector.getEstado_lector());
        if(lector.getEstado_lector()){
            habilitarCampos();
            
        }else{
            anularCampos();
        }
    }//GEN-LAST:event_jbBuscarLectorActionPerformed

    private void jcbEstadoLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoLectorActionPerformed
       
    }//GEN-LAST:event_jcbEstadoLectorActionPerformed

    private void jbBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarLibroActionPerformed
        String nombreLibro=jtNombreLibro.getText();
        if(nombreLibro!=null){
            limpiarTabla();
            llenarConLibros();
            jbRegistrar.setEnabled(true);
        }
    }//GEN-LAST:event_jbBuscarLibroActionPerformed

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        int fe=jtLibros.getSelectedRow();
        if(fe!=-1){
            
            Prestamo pres=new Prestamo();
            Ejemplar ejemplar=ejeda.BuscarEjemplarID((Integer)modelo.getValueAt(fe, 0));
            Lector lector= new Lector();
            try{
            int id=Integer.parseInt(jtIdLector.getText());
            lector=leda.buscarLector(id);
            pres.setEjemplar(ejemplar);
            pres.setLector(lector);
            pres.setEstado(true);
            LocalDate fecha=jdcFechaPrestamo.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            pres.setFecha_prestamo(fecha);
            
            prestamo.registrarPrestamo(pres);
            
            limpiarTabla();
        jtNombreLector.setText("");
        jtApellidoLector.setText("");
        jtDniLector.setText("");
        jtNombreLibro.setText("");
        jdcFechaPrestamo.cleanup();
        anularCampos();
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Error en id");
        }
            
        }else{
            JOptionPane.showMessageDialog(this, "No se selecciono una columna");
        }
    }//GEN-LAST:event_jbRegistrarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
      limpiarTabla();
      jtNombreLector.setText("");
        jtApellidoLector.setText("");
        jtDniLector.setText("");
        jtNombreLibro.setText("");
        jdcFechaPrestamo.cleanup();
        anularCampos();
      
      
    }//GEN-LAST:event_jbLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbBuscarLector;
    private javax.swing.JButton jbBuscarLibro;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JCheckBox jcbEstadoLector;
    private com.toedter.calendar.JDateChooser jdcFechaPrestamo;
    private javax.swing.JTextPane jtApellidoLector;
    private javax.swing.JTextPane jtDniLector;
    private javax.swing.JTextPane jtIdLector;
    private javax.swing.JTable jtLibros;
    private javax.swing.JTextPane jtNombreLector;
    private javax.swing.JTextPane jtNombreLibro;
    // End of variables declaration//GEN-END:variables
}
