/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import entidades.Autor;
import entidades.Ejemplar;
import entidades.Libro;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Conexion;
import modelo.EjemplarData;
import modelo.LibroData;

/**
 *
 * @author Ezequiel Coronel
 */
public class ViewEjemplar extends javax.swing.JInternalFrame {

    private LibroData ld;
    private EjemplarData ed;

    public ViewEjemplar() {
        initComponents();
        Conexion c = new Conexion();
        ld = new LibroData(c);
        ed = new EjemplarData(c);
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbLibros = new javax.swing.JComboBox<>();
        jbCargarEjemplares = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfCantEjemplares = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Carga de ejemplares");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Libro:");

        jcbLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLibrosActionPerformed(evt);
            }
        });

        jbCargarEjemplares.setText("Cargar Ejemplares");
        jbCargarEjemplares.setEnabled(false);
        jbCargarEjemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCargarEjemplaresActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cant. de ejemplares a cargar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jcbLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(jtfCantEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbCargarEjemplares)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalir)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCantEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCargarEjemplares)
                    .addComponent(jbSalir))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbCargarEjemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCargarEjemplaresActionPerformed
        try {
            int cantEjemplares = Integer.parseInt(jtfCantEjemplares.getText());

            if (cantEjemplares > 0) {
                Libro libro = (Libro) jcbLibros.getSelectedItem();
                Ejemplar ejemplar = new Ejemplar(libro, "Disponible");
                ed.agregarEjemplares(ejemplar, cantEjemplares);
                jcbLibros.setSelectedIndex(-1);
                jtfCantEjemplares.setText("");
                jbCargarEjemplares.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(this, "Ingrese una cantidad valida de ejemplares!");
                jtfCantEjemplares.requestFocus();
            }

        } catch (NullPointerException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Se necesita una cantidad en numeros de ejemplares!");
            jtfCantEjemplares.requestFocus();
        }
    }//GEN-LAST:event_jbCargarEjemplaresActionPerformed

    private void jcbLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLibrosActionPerformed
        if (jcbLibros.getSelectedIndex() > -1) {
            jbCargarEjemplares.setEnabled(true);
        } else {
            jbCargarEjemplares.setEnabled(false);
        }
    }//GEN-LAST:event_jcbLibrosActionPerformed

    public void llenarCombo() {
        List<Libro> libros = ld.getAll();
        for (Libro l : libros) {
            jcbLibros.addItem(l);
        }
        jcbLibros.setSelectedIndex(-1);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbCargarEjemplares;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Libro> jcbLibros;
    private javax.swing.JTextField jtfCantEjemplares;
    // End of variables declaration//GEN-END:variables
}
