/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import entidades.Ejemplar;
import javax.swing.JOptionPane;
import modelo.Conexion;
import modelo.EjemplarData;

/**
 *
 * @author Ezequiel Coronel
 */
public class ViewEjemplarBusqueda extends javax.swing.JInternalFrame {

    private EjemplarData ed;

    public ViewEjemplarBusqueda() {
        initComponents();
        Conexion c = new Conexion();
        ed = new EjemplarData(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfCodigoEjemplar = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfEstadoActualEjemplar = new javax.swing.JTextField();
        jbActualizarEjemplar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtfNombreLibro = new javax.swing.JTextField();
        jtfIsbnLibro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfAutorLibro = new javax.swing.JTextField();
        jbLimpiar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jcbEstadosEjemplar = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Busqueda de ejemplar");

        jLabel2.setText("Codigo de ejemplar(id):");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Estado Actual:");

        jtfEstadoActualEjemplar.setEditable(false);

        jbActualizarEjemplar.setText("Actualizar");
        jbActualizarEjemplar.setEnabled(false);
        jbActualizarEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarEjemplarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel4.setText("Libro:");

        jtfNombreLibro.setEditable(false);

        jtfIsbnLibro.setEditable(false);

        jLabel5.setText("ISBN:");

        jLabel6.setText("Autor:");

        jtfAutorLibro.setEditable(false);

        jbLimpiar.setText("Limpiar");
        jbLimpiar.setEnabled(false);
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jLabel7.setText("Nuevo Estado:");

        jcbEstadosEjemplar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prestado", "Retraso", "Reparacion", "Disponible" }));
        jcbEstadosEjemplar.setSelectedIndex(-1);
        jcbEstadosEjemplar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbActualizarEjemplar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLimpiar)
                .addGap(33, 33, 33)
                .addComponent(jbSalir)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jtfNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6)
                                .addComponent(jtfCodigoEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfIsbnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbEstadosEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfEstadoActualEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfCodigoEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfIsbnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEstadoActualEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbEstadosEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbActualizarEjemplar)
                    .addComponent(jbSalir)
                    .addComponent(jbLimpiar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        try {
            int codigoEjemplar = Integer.parseInt(jtfCodigoEjemplar.getText());
            Ejemplar ejemplar = ed.buscarEjemplar(codigoEjemplar);
            if (codigoEjemplar > 0) {
                if (ejemplar != null) {
                    jtfNombreLibro.setText(ejemplar.getLibro().getNombre());
                    jtfIsbnLibro.setText(String.valueOf(ejemplar.getLibro().getISBN()));
                    jtfAutorLibro.setText(ejemplar.getLibro().getAutor().getNombreAutor() + " " + ejemplar.getLibro().getAutor().getApellidoAutor());
                    jtfEstadoActualEjemplar.setText(ed.estadoEjemplar(codigoEjemplar));

                    jtfCodigoEjemplar.setEnabled(false);
                    jbBuscar.setEnabled(false);
                    jcbEstadosEjemplar.setEnabled(true);
                    jbActualizarEjemplar.setEnabled(true);
                    jbLimpiar.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "No hay un ejemplar con ese codigo!");
                    jcbEstadosEjemplar.setSelectedIndex(-1);
                    jcbEstadosEjemplar.setEnabled(false);
                    jbActualizarEjemplar.setEnabled(false);
                    jbLimpiar.setEnabled(false);
                    jtfCodigoEjemplar.requestFocus();

                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un codigo de ejemplar valido!");
                limpiarTextFields();
                jcbEstadosEjemplar.setSelectedIndex(-1);
                jcbEstadosEjemplar.setEnabled(false);
                jbActualizarEjemplar.setEnabled(false);
                jbLimpiar.setEnabled(false);
                jtfCodigoEjemplar.requestFocus();
            }

        } catch (NullPointerException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Se necesita un codigo de ejemplar valido!");
            jcbEstadosEjemplar.setSelectedIndex(-1);
            jcbEstadosEjemplar.setEnabled(false);
            jtfCodigoEjemplar.setText("");
            jtfCodigoEjemplar.requestFocus();
        }

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        limpiarTextFields();
        jtfCodigoEjemplar.setEnabled(true);
        jbBuscar.setEnabled(true);
        jtfCodigoEjemplar.requestFocus();
        jbBuscar.setEnabled(true);
        jbActualizarEjemplar.setEnabled(false);
        jcbEstadosEjemplar.setSelectedIndex(-1);
        jcbEstadosEjemplar.setEnabled(false);
        jbLimpiar.setEnabled(false);
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbActualizarEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarEjemplarActionPerformed
        int codigoEjemplar = Integer.parseInt(jtfCodigoEjemplar.getText());

        if (jcbEstadosEjemplar.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un estado para actualizar al lector!");
            jcbEstadosEjemplar.requestFocus();
        } else {
            int confirmarActualizacion = JOptionPane.showConfirmDialog(this, "Se esta por actualizar el estado del Ejemplar ¿Está seguro?");

            if (JOptionPane.OK_OPTION == confirmarActualizacion) {
                Ejemplar ejemplar = ed.buscarEjemplar(codigoEjemplar);
                String nuevoEstado = (String) jcbEstadosEjemplar.getSelectedItem();
                ed.actualizarEstado(ejemplar, nuevoEstado);
                JOptionPane.showMessageDialog(this, "Se actualizo el estado del ejemplar!");
                
                limpiarTextFields();
                jtfCodigoEjemplar.setEnabled(true);
                jbBuscar.setEnabled(true);
                jbActualizarEjemplar.setEnabled(false);
                jbLimpiar.setEnabled(false);
                jcbEstadosEjemplar.setSelectedIndex(-1);
                jcbEstadosEjemplar.setEnabled(false);
                jtfCodigoEjemplar.requestFocus();
            }else{
                JOptionPane.showMessageDialog(this, "Se cancelo la actualizacion del estado del ejemplar");
            }
        }
    }//GEN-LAST:event_jbActualizarEjemplarActionPerformed

    public void limpiarTextFields() {
        jtfCodigoEjemplar.setText("");
        jtfNombreLibro.setText("");
        jtfIsbnLibro.setText("");
        jtfAutorLibro.setText("");
        jtfEstadoActualEjemplar.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbActualizarEjemplar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcbEstadosEjemplar;
    private javax.swing.JTextField jtfAutorLibro;
    private javax.swing.JTextField jtfCodigoEjemplar;
    private javax.swing.JTextField jtfEstadoActualEjemplar;
    private javax.swing.JTextField jtfIsbnLibro;
    private javax.swing.JTextField jtfNombreLibro;
    // End of variables declaration//GEN-END:variables
}
